[build]
  functions = "functions" # Adjust this if your functions are in a different folder
  publish = "dist" # Adjust this if your static files are in a different folder
   command = "npm run build"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
